const UNEXPECTED_ERROR_CODE = 1000;
const INVALID_INPUT_ERROR_CODE = 1001;
const INVALID_EMAIL_ERROR_CODE = 1002;
const DUPLICATE_KEY_ERROR_CODE = 1003;
const USER_NOT_FOUND_ERROR_CODE = 1004;
const INVALID_PASSWORD_ERROR_CODE = 1005;
const INVALID_CARD_OWNER_ERROR_CODE = 1007;

module.exports = {
  UNEXPECTED_ERROR_CODE,
  INVALID_INPUT_ERROR_CODE,
  INVALID_EMAIL_ERROR_CODE,
  DUPLICATE_KEY_ERROR_CODE,
  USER_NOT_FOUND_ERROR_CODE,
  INVALID_PASSWORD_ERROR_CODE,
  INVALID_CARD_OWNER_ERROR_CODE,
};
