definitions:
  CreateUserRequestBody:
    type: object
    required:
      - email
      - password
      - firstName
      - lastName
    properties: 
      email:
        type: string
        description: User email address
        example: address@some.info
      password:
        type: string
        description: User password
        example: Testing123
      firstName:
        type: string
        description: User first name
        example: John
      lastName:
        type: string
        description: User last name
        example: Doe
      isEnabled:
        type: boolean
        description: Defines if user is enabled
        example: true
  CreateUserResponse:
    type: object
    properties:
      id: 
        type: string
        description: the object id of user
        example: 63cf93dfb9a474672bedd8c3
      email: 
        type: string
        description: the object id of user
        example: address@some.info
      firstName:
        type: string
        description: User first name
        example: John
      lastName:
        type: string
        description: User last name
        example: Doe
  GetAccountResponse:
    type: object
    properties:
      id: 
        type: string
        description: the object id of user
        example: 63cf93dfb9a474672bedd8c3
      iban: 
        type: string
        description: iban number
        example: BGSTSA10BG131231231231
      currency:
        type: string
        description: the currency of the account
        example: BGN
      isEnabled:
        type: boolean
        description: determines if the account is enabled
        example: true
      balance:
        type: number
        description: balance of the account
        example: John
  UnexpectedErrorResponse:
    properties:
      error:
        type: string
        description: Unexpected error message
        example: Something went wrong
      errorCode:
        type: number
        description: Error code
        example: 500
  UnauthorizedErrorResponse:
    properties:
      error:
        type: string
        example: Unauthorized request
      errorCode:
        type: number
        example: 1008