const UNEXPECTED_ERROR_CODE = 1100;
const INVALID_INPUT_ERROR_CODE = 1101;
const INVALID_EMAIL_ERROR_CODE = 1102;
const DUPLICATE_KEY_ERROR_CODE = 1103;
const USER_NOT_FOUND_ERROR_CODE = 1104;

module.exports = {
  UNEXPECTED_ERROR_CODE,
  INVALID_INPUT_ERROR_CODE,
  INVALID_EMAIL_ERROR_CODE,
  DUPLICATE_KEY_ERROR_CODE,
  USER_NOT_FOUND_ERROR_CODE,
};
