const UNEXPECTED_ERROR_CODE = 1400;
const INVALID_INPUT_ERROR_CODE = 1401;
const INVALID_EMAIL_ERROR_CODE = 1402;
const DUPLICATE_KEY_ERROR_CODE = 1403;
const USER_NOT_FOUND_ERROR_CODE = 1404;
const EXPIRED_CARD_ERROR_CODE = 1405;

module.exports = {
  UNEXPECTED_ERROR_CODE,
  INVALID_INPUT_ERROR_CODE,
  INVALID_EMAIL_ERROR_CODE,
  DUPLICATE_KEY_ERROR_CODE,
  USER_NOT_FOUND_ERROR_CODE,
  EXPIRED_CARD_ERROR_CODE,
};
